### PR TITLE
Lesson_1_6 Reusable components, imperative React

### PR DESCRIPTION
**Pull request by raul-2001**

### CODE REVIEW

**Review by gsiryvhb — APPROVED** [review]
looks good @raul-2001

**Comment by raul-2001** [comment]
Hi. Dear, is that means succesful assignment ?

**Comment by gsiryvhb** [comment]
@raul-2001 yes - I have also marked the review form as successful

**Comment by raul-2001** [comment]
Thank yoi so much, Sir.

**Pull request merged**
