### PR TITLE
lesson 1-4

### PR DESCRIPTION
**Pull request by raul-2001**

### CODE REVIEW

**Review by gsiryvhb — CHANGES_REQUESTED** [review]
@raul-2001

**Review by gsiryvhb — CHANGES_REQUESTED** [review]
Also it appears that you are declaring your functions with let - that is incorrect 
the proper declaration should be 
`**const** functionName =()=>{
}`

**Review by gsiryvhb — APPROVED** [review]

**Review by gsiryvhb — CHANGES_REQUESTED** [review]
@raul-2001 Raul, please read the instructions for the assignment - You are supposed to use props destructuring that means that you should not use the word "props" in your code but reference the prop name that you are passing

**Comment by raul-2001** [comment]
Hi dear, I have resolved above pointed mistakes. Could you pls review my code again. Thanks.

**Review by gsiryvhb — APPROVED** [review]
great job!

**Comment by raul-2001** [comment]
Thank you for reviewing my code.

**Pull request merged**
